# Generated by Django 3.2.20 on 2023-11-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_proj', '0002_auto_20231124_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
